name: "Deploy React + Vite to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          PROJECT_ID: dicompostelyu
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/dicompostelyu/dicomposfrontend:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/dicompostelyu/dicomposfrontend:latest
          service: dicompos-frontend-prod
          region: asia-southeast2
          platform: managed
          allow-unauthenticated: true
          timeout: 3m
